cache:
 paths:
 - node_modules/

variables:
  build_env: 'ci'

stages:
  - deploy

# production
production-release:
  stage: deploy
  only:
    - master
  script:
    - dpl --provider=heroku --app=meiko2017 --api-key=$HEROKU_API_KEY